spring:
  datasource:
    url: jdbc:postgresql://maglev.proxy.rlwy.net:29316/railway
    username: postgres
    password: ZneKYCwWyaXAPPLTAMgHGoBpurWgFjRX
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    org:
      springframework:
        web: DEBUG

stripe:
  token: "rk_test_51RNeLsCAbO7fQUZ4rQAfDgCQqFvg9WI2xjcDenPAeA55FnW0XPBw3wkLHaXdaS843m3geoSA1ITpyEx7lFD6Alt600xqn7AOYw"

springdoc:
  api-docs:
    path: /swagger/v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

server:
  port: ${PORT:8080}

security:
  jwt:
    secret: key

twilio:
  account-sid: AC59e732193113b0866c4ce6583872c604
  auth-token: a612ca3b6e6b3a5cd48134153bb2d6c8
  whatsapp-number: "+19478885568"